name: MovementPlusPlus
main: com.trinoxtion.movement.MovementPlusPlus
version: 1.9.7.2
api-version: 1.15
description: Support for custom movement systems!

##Todo: make movementsystems definable in-game