name: MovementPlusPlus
main: com.trinoxtion.movement.MovementPlusPlus
version: 1.9.7.3 Spike 9
api-version: 1.19
description: Support for custom movement systems!

##Todo: make movementsystems definable in-game