name: MovementPlusPlus
main: com.trinoxtion.movement.MovementPlusPlus
version: 1.9.7
api-version: 1.13
description: Support for custom movement systems!

##Todo: make movementsystems definable in-game