name: MovementPlusPlus
main: com.trinoxtion.movement.MovementPlusPlus
version: 1.10.1 Indev 18
api-version: 1.20
depend: [PunchTree-Util]
description: Support for custom movement systems!

##Todo: make movementsystems definable in-game

commands:
  mvtest:
  mvclear:
  summon-grapple-target:
    permission: movementplusplus.summon-grapple-target
  grapple-wand:
    permission: movementplusplus.grapple-wand