name: MovementPlusPlus
main: com.trinoxtion.movement.MovementPlusPlus
version: 1.9.8 Spike 15
api-version: 1.19
depend: [PunchTree-Util]
description: Support for custom movement systems!

##Todo: make movementsystems definable in-game

commands:
  mvtest:
  mvclear: