name: MovementPlusPlus
main: com.trinoxtion.movement.MovementPlusPlus
version: 1.9.6.3.1
api-version: 1.13
description: Support for custom movement systems!

##Todo: make movementsystems definable in-game